name: rick_and_morty_api
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.6
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  http: ^0.13.4
  equatable: ^2.0.0
  shared_preferences: ^2.0.13
  ionicons: ^0.1.2
  flutter_screenutil: ^5.5.4
  flutter_riverpod: ^2.0.2
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  flutter_gen_runner: ^4.3.0
  simple_gradient_text: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.1
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true



flutter:
  uses-material-design: true
  assets:
   - assets/icons/fileok.svg
   - assets/icons/filedebt.svg
   - assets/icons/search.svg
   - assets/icons/top.svg
   - assets/icons/nopayments.svg
   - assets/icons/nocontracts.svg
   - assets/icons/cross.svg
   - assets/icons/time.svg

fonts:
  - family: HelveticaNeueCyr
    fonts:
      - asset: assets/fonts/HelveticaNeueCyr-Light.ttf
        weight: 300
      - asset: assets/fonts/HelveticaNeueCyr-Roman.ttf
        weight: 400
      - asset: assets/fonts/HelveticaNeueCyr-Medium.ttf
        weight: 500

